### ISSUE TITLE
Support for schema qualified tables

### ISSUE THREAD

**Issue by marcel-meyer** [malthe/pq#35]
Hi there,
I would like to place my queue table in a schema other than `public`.
When I set the `table` arg to a schema qualified table name, the following error occurs:
```
Traceback (most recent call last):
  File "worker.py", line 139, in <module>
    for job in queue:
  File "/Users/marcel/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pq/__init__.py", line 86, in next
    return QueueIterator.__next__(self)
  File "/Users/marcel/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pq/__init__.py", line 81, in __next__
    return self.queue.get(timeout=self.timeout)
  File "/Users/marcel/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pq/__init__.py", line 176, in get
    cursor, block
  File "/Users/marcel/.pyenv/versions/2.7.15/lib/python2.7/site-packages/pq/utils.py", line 69, in wrapper
    cursor.execute("PREPARE %s AS\n%s" % (name, query), d)
psycopg2.ProgrammingError: syntax error at or near "."
LINE 1: PREPARE _pull_item_fsm.queue_test_fsm.queue AS
```

Is this possible?
Regards,
Marcel

**Comment by malthe** [comment]
Perhaps a decent workaround would be to issue this command on your connection (through an open  cursor):
```python
cursor.execute("SET search_path TO " + schema_name)
```
But it would be nice to have a `schema` option.

**Comment by riyadparvez** [comment]
Is there any update on this issue?

**Comment by ThibTrip** [comment]
Hello @riyadparvez it works on the master (as of writing this reply, version `1.9.1-dev`) but not on the current PyPI version (`1.9.0`).
So if you clone the master and install with `pip install .` (or `pip install -e .` for editing the library) inside the cloned folder such a code will work (assuming the postgres schema already exists):

```
import pq

queue = pq.PQ(conn=conn, # some psycopg2 connection
              schema='queues', table='my_jobs')
queue.create()
```

**Comment by cruisecraig** [comment]
Thanks for this @malthe. It looks like there may be a problem with `schema` vs `db` here as I get the following error

```
  File "/Users/craig.quiter/miniconda3/envs/galileo-scopes/lib/python3.7/site-packages/pq/utils.py", line 73, in wrapper
    cursor.execute("PREPARE %s AS\n%s" % (identifier, query), d)
psycopg2.errors.FeatureNotSupported: cross-database references are not implemented: "my_branch.public.transformer_queue"
LINE 4:         SELECT * FROM my_branch.public.transformer_queue
```

Whereas the query should be

```
SELECT * FROM my_branch.transformer_queue
```

OR 

```
SELECT * FROM my_db_name.my_branch.transformer_queue
```

`public` is the default schema and the one I'm trying not to use. Thanks again!!!
